### ISSUE TITLE
Python 2 or 3?

### ISSUE THREAD

**Issue by cclauss** [mikaelho/pythonista-lambda-deploy#2]
Does https://github.com/mikaelho/pythonista-lambda-deploy/blob/master/lambda-deploy.py#L169 run the function in Python 2?  Or am I just misreading it?

**Comment by mikaelho** [comment]
Thanks, changed to 3.6. Could add a magic string for using 2.7, but only if someone needs it.

**Comment by cclauss** [comment]
I helped to get the open source Apache OpenWhisk function-as-a-service to Python 3.6.1...

https://github.com/apache/incubator-openwhisk/issues/1184#issuecomment-285323326

https://medium.com/openwhisk/openwhisk-loves-python-3-and-you-should-too-d9f914fdc1d6

**Comment by mikaelho** [comment]
OpenWhisk looks interesting, of course. Is there a deployment option for Pythonista users specifically?

**Comment by cclauss** [comment]
Not yet but your work has me inspired to create something Pythonista specific out of https://github.com/cclauss/openwhisk_python

**Comment by mikaelho** [comment]
Whatever you would create would probably be much more comprehensive, but just being able to say @openwhisk instead of @awslambda in this script would appeal in its simplicity.

**Comment by cclauss** [comment]
Nice idea.   Let me get it up and stumbling first and then we can drive towards convergence.
